### ISSUE TITLE
Rework Iteration Class

### ISSUE THREAD

**Issue by carstenuhlig** [Rostlab/nala#20]
Rework the iteration class, so that in general we can use it with a script and update it (mergedannotations, etc.)
#### todo
- [x] include merged annotations
- [x] PrepareDatasetPipeline specific to mutations, etc. (make subclasses)
- [x] featuregenerators in constructor
- [ ] automatic recalculation of missing iterations

@abojchevski please add tasks that must be done
@jmcejuela when you see something that should be changed, add this to the list
