### ISSUE TITLE
Very last experiments

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/nala#58]
We go for:
- BIEO labeling (after agreeing on a good balance between tmVar_training, nala_training, and being significantly better on exact measures)
- pruning parts
- no combination of models
- nala_training
- word_embeddings model = `word_embeddings_2016-03-28`, a=0, m=1
- ~~--nl features (threshold=0 no window)~~
- _no_ elastic net

```
$train_cv --training_corpus nala_training --pruner parts --labeler BIEO --word_embeddings --we_additive 0 --we_multiplicative 1

# class tp      fp      fn      fp_ov   fn_ov   match   P       P_SE    R       R_SE    F       F_SE    match   P       P_SE    R       R_SE    F       F_SE
0       757     142     169     90      105     e       0.8420  0.0039  0.8175  0.0037  0.8296  0.0034  o       0.9482  0.0023  0.9370  0.0022  0.9426  0.0019
1       229     338     465     270     287     e       0.4039  0.0038  0.3300  0.0033  0.3632  0.0034  o       0.9204  0.0017  0.8154  0.0027  0.8647  0.0019
2       40      70      105     49      61      e       0.3636  0.0108  0.2759  0.0097  0.3137  0.0114  o       0.8772  0.0089  0.7732  0.0095  0.8219  0.0058
T   1026    550     739     409     453     e       0.6510  0.0032  0.5813  0.0032  0.6142  0.0031  o       0.9305  0.0014  0.8684  0.0019  0.8984  0.0014
```

`$train_cv --training_corpus nala_training --pruner parts --labeler IO --word_embeddings --we_additive 0 --we_multiplicative 1  # --cv_n 5` 

```
# class tp  fp  fn  fp_ov   fn_ov   match   P   P_SE    R   R_SE    F   F_SE    match   P   P_SE    R   R_SE    F   F_SE
0   765 163 171 97  108 e   0.8244  0.0038  0.8173  0.0034  0.8208  0.0033  o   0.9363  0.0026  0.9390  0.0019  0.9377  0.0018
1   207 464 494 379 315 e   0.3085  0.0036  0.2953  0.0033  0.3017  0.0033  o   0.9138  0.0017  0.8343  0.0025  0.8722  0.0017
2   36  94  109 61  61  e   0.2769  0.0094  0.2483  0.0088  0.2618  0.0104  o   0.8272  0.0094  0.7670  0.0099  0.7960  0.0057
T   1008    721 774 537 484 e   0.5830  0.0034  0.5657  0.0033  0.5742  0.0032  o   0.9169  0.0013  0.8749  0.0017  0.8954  0.0012
```

---
- [x] ST: **nala_training** vs IDP4+_training
- [x] all3: **nala_training** vs IDP4+_training
- [x] ST: **del None** vs del 1,2
- [x] all3: **del None** vs del 1,2
- [x] ST: **parts** vs sentences (...) pruning
- [x] all3: **sentences + ST + NL** vs other
- [x] ST: **BIEO** and **IO** equally good, **BIO** very slightly worse. We could go for **IO** since there NL is also good
- [x] all3: **BIO** (IO equal in NL F1 but worse for SS)
- [x] **no elastic net**

---
- All3 baseline: https://github.com/abojchevski/nala/issues/58#issuecomment-202509068
- ST baseline: https://github.com/abojchevski/nala/issues/58#issuecomment-202290962

---
- [x] **nala_training_BIEO_del_1,2** vs nala_training_11_del_1,2 --> test label on ST --> BIEO
- [x] Verify that there is no bug in benchmarking. Somehow WE doesn't yield benefits now --> I cannot find any error. I also manually checked using tagtog and documents seemed to be very well annotated
- [x] **ST-only IDP4+_training** vs nala_training (in CV) https://github.com/abojchevski/nala/issues/63#issuecomment-201358529 --> Use IDP4+_training for ST (and use parts pruning)
- [x] **Do use elastic net for all3** :-)
- [x] ...running... ST elastic net
- [x] feature.possible_states=BOOL --> no! It decreased the performance in about 1 point for NL. ALso the training only took slightly more, not _drastically_
- [x] **WE with number replacement** vs no: https://github.com/abojchevski/nala/issues/61
- [x] we features in window --> no
- [x] **we features improve all3 model** --> Yes
- [x] **do use we in all3 with a=2 & m=3** we hyperparameters (https://github.com/abojchevski/nala/issues/21)
- [x] **do not use we for ST model** (Performance decreases otherwise very slightly (-0.0003) or otherwise doesn't change. Setting high we weights decreases performance in 0.007 for a=4&m=4)
- [x] **Part pruning for ST model**
- [x] **Sentence pruning with highrecall NL mentions for all3 model**
- [x] Delete class 1 in all3 model with before pruning --> much worse, 2 points less F1 NL
- [x] Post-processing fix issues at the end too --> doesn't do anything
- [x] **Post-processing more rules to improve exact** --> improves on smaller sets, doesn't seem to improve in large ones (see https://github.com/abojchevski/nala/commit/710376621c374cc1b9f3024e9f86b5875dc018c5)
- [x] **New postprocessing rule: follow the rule of abbreviations + first gene mutation (then protein mutation)** --> https://github.com/abojchevski/nala/commit/6683ae4de13dc2806ae0d5c2f3fe7b278bd52b5f
- [x] Final merge of models
